---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: HydrogenOS
# description will be included in the image's metadata
description: Beautiful and feature-rich KDE-based operating system with an Oxygen-focused design

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - plasma-oxygen
      - oxygen-sounds
      - oxygen-fonts
      - oxygen-icon-theme
      - oxygen-sound-theme
      - oxygen-cursor-themes
      - oxygen-gtk2
      - qt5-style-oxygen
      - plasma-oxygen-qt5
      - plasma-oxygen-qt6
      - kvantum
      - konqueror
      - kmix
      - ksystemlog
      - k3b
      - sweeper
      - kmag
      - kmousetool
      - krecorder
      - kmouth
      - strawberry
    remove:
      # example: removing firefox (in favor of the flatpak) (or in my case, in favor of Konqueror. Go ahead, make fun of me.)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - kjournald-libs
      - kjournald
      - kdebugsettings
      - nvtop

#  - type: default-flatpaks
#    notify: true # Send notification after install/uninstall is finished (true/false)
#    system:
#      # If no repo information is specified, Flathub will be used by default
#      install:
#        - 
#      remove:
#        - 
#    user: {} # Also add Flathub user repo, but no user packages

  - type: yafti # user choice!
  - type: script
    snippets:
    - "flatpak override --env=QT_STYLE_OVERRIDE=fusion"
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
  - type: initramfs # plymouth theming